# Generated by Django 6.0.6 on 2026-08-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['id']},
        ),
    ]
