# Generated by Django 6.0.6 on 2026-08-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0006_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
