# Generated by Django 6.0.6 on 2026-07-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='title',
        ),
    ]
