# Generated by Django 6.0.6 on 2026-08-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_comment_productfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='app_shop.product'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
