# Generated by Django 6.0.6 on 2026-08-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0010_alter_comment_product_alter_productfeature_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.product'),
        ),
    ]
