# Generated by Django 6.0.6 on 2026-08-05 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_cart_quantity'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.PositiveBigIntegerField()),
                ('paid_amount', models.IntegerField()),
                ('address_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('registered', 'ثبت شده'), ('preparing', 'در حال آماده سازی'), ('shipped', 'ارسال شده')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_addresses', to='contenttypes.contenttype')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_order.cart')),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_profiles', to='contenttypes.contenttype')),
            ],
        ),
    ]
