# Generated by Django 6.0.6 on 2026-08-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
